#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# npx lint-staged

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
npm run check-format ||
(
    echo '🤢🤮🤢🤮 Your styling need formatting. 🤢🤮🤢🤮
            Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
        echo '😤🏀👋😤
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.
                 😤🏀👋😤 '
        false; 
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
